### PR TITLE
More design fixes

### PR DESCRIPTION
**Pull request by bainco**
More small design fixes for the landing page.

These were mentioned in #8 but didn't make it in.

### CODE REVIEW

**Comment by snpradhan** [comment]
Can you verify these changes in your local dev environment and make sure they work as expected.

**Comment by bainco** [comment]
The following changes have been verified locally (on Safari and Chrome; can provide version numbers if necessary):

- [ ] Fix form text to black 
- [ ] Remove unnecessary dialog box
- [ ] Increase line height on modal links
- [ ] Increase header height
- [ ] Make header login an actual button (@snpradhan You should double check my CSS override removal here just incase I've failed to consider some element down the tree)
- [ ] Remove Facebook comments by request (see 103537c)

I'm assuming that we don't need a particularly clean commit history on this repo since it's just a couple of people, but I can clean this PR up if you want.

**Comment by snpradhan** [comment]
The commit history on the dev branches does not need to be clean.  However, I would like to keep the master branch clean.  I will cherry pick the commits and merge with master.

**Comment by snpradhan** [comment]
All of the above commits have been verified and pushed to Stage.  These will be pushed to production later today.

**Pull request closed without merging**
